---
title: "Reporting Engine"
output: flexdashboard::flex_dashboard
runtime: shiny
---


```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(rmarkdown)
library(knitr)
library(Hmisc)
library(DT)

library(data.table)
assignInNamespace("cedta.override", c(data.table:::cedta.override,"rmarkdown"), "data.table")


opts_chunk$set(echo = FALSE, comment="", warning = FALSE, message = FALSE, tidy.opts=list(width.cutoff=55), tidy = TRUE)

```


```{r read_data, include=FALSE, eval = TRUE}
dat <- fread(input = "../Data/Homework 3 Data.csv", verbose = FALSE)
```


```{r constants}
id.name <- "id"
age.name <- "Age"
gender.name <- "Gender"
income.name <- "Income"
region.name <- "Region"
persona.name <- "Persona"

product.name <- "Product"
awareness.name <- "Awareness"
consideration.name <- "Consideration"
consumption.name <- "Consumption"
satisfaction.name <- "Satisfaction"
advocacy.name <- "Advocacy"
Aggregated.Engagement.name <- "Aggregated.Engagement"

pattern.bp <- "BP_"

age.group.name <- "Age Group"
income.group.name <- "Income Group"

cuts.age <- c(18, 35, 50, 65, 120)
cuts.income <- 1000* c(0, 50, 75, 100, 150, 250)

dat[, eval(age.group.name) := cut2(x = get(age.name), cuts = cuts.age)]
dat[, eval(income.group.name) := cut2(x = get(income.name), cuts = cuts.income)]
dat[, eval(satisfaction.name) := get(satisfaction.name)/10]

unique.age.groups <- dat[, unique(get(age.group.name))]
unique.genders <- dat[, unique(get(gender.name))]
unique.income.groups <- dat[, unique(get(income.group.name))]
unique.regions <- dat[, unique(get(region.name))]
unique.personas <- dat[, unique(get(persona.name))]

unique.products <- dat[, unique(get(product.name))]
num.products <- length(unique.products)

respondent.variables <- c(age.group.name, gender.name, income.group.name, region.name, persona.name)
states.of.engagement <- c(awareness.name, consideration.name, consumption.name, satisfaction.name, advocacy.name)
bp.traits <- names(dat)[grep(pattern = pattern.bp, x = names(dat))]

negative_perceptions <- c("BP_Boring_0_10","BP_Bulky_0_10" ,"BP_Fragile_0_10","BP_Expensive_0_10")
```

```{r functions}
percentage.table <- function(x, digits = 1){
  tab <- table(x)
  percentage.tab <- 100*tab/(sum(tab))
  rounded.tab <- round(x = percentage.tab, digits = digits)
  return(rounded.tab)
}

round.numerics <- function(x, digits){
  if(is.numeric(x)){
    x <- round(x = x, digits = digits)
  }
  return(x)
}
mean.diff <- function(x, y){
  return(mean(x, na.rm=TRUE) - mean(y, na.rm=TRUE))
}

```


Introduction
=====================================  

We are analyzing data from the Marketing Department covering a variety of mobile phone products.  

The survey was given to `r dat[, length(unique(get(id.name)))]` respondents and covered `r num.products` separate products.

Click on the tabs to see different reports.


Question 1
===================================


Row {data-height=500}
-------------------------------------

```{r respondents}
inputPanel(
  selectInput(inputId="respondent_variable", label = "Select Variable:", choices = respondent.variables, selected = respondent.variables[1])
)


renderPlot({
  tab <- percentage.table(x = dat[get(product.name) == get(product.name)[1], get(input$respondent_variable)])
  barplot(height = tab, space=0.01, las = 1, main = input$respondent_variable, ylab = "Percentage", xlab = input$respondent_variable, ylim = c(0, 1.2*max(tab, na.rm = TRUE)), col = "dodgerblue")

  space_val = 0
  text(x = -0.4 + 1:length(tab) * (1+space_val), y = tab, labels = sprintf("%.1f%%", tab), pos = 3)
})

```

Question 2
=====================================  


Row {data-height=800}
-------------------------------------

```{r products}
inputPanel(
  selectInput(inputId = "product_info_engagement_state", label = "Select State of Engagement:", choices = states.of.engagement, selected = states.of.engagement[1]),
  selectInput(inputId="product_age_group", label = "Age Group", choices = unique.age.groups, selected = unique.age.groups, multiple = TRUE),
  selectInput(inputId = "product_gender", label = "Gender", choices = unique.genders, selected = unique.genders, multiple = TRUE),
  selectInput(inputId = "product_income_group", label = "Income Group", choices = unique.income.groups, selected = unique.income.groups, multiple = TRUE),
  selectInput(inputId = "product_region", label = "Region", choices = unique.regions, selected = unique.regions, multiple = TRUE),
  selectInput(inputId = "product_persona", label = "Persona", choices = unique.personas, selected = unique.personas, multiple = TRUE),

  sliderInput(inputId = "product_Top_products", label = "# of Products shown", min = 0, max = 20, value = 5, step = 1)
)

renderPlot({
  subdat <- dat[get(age.group.name) %in% input$product_age_group & get(gender.name) %in% input$product_gender & get(income.group.name) %in% input$product_income_group & get(region.name) %in% input$product_region & get(persona.name) %in% input$product_persona]
  rates <- subdat[, .(Mean = 100*mean(get(input$product_info_engagement_state), na.rm=TRUE)), by = product.name]

  setorderv(x = rates, cols = "Mean", order = -1)
  sub_rates <- rates[1:input$product_Top_products]

  barplot <- barplot(height = sub_rates[,Mean], space=0.01, las = 1, main = input$product_info_engagement_state, ylab = sprintf("Rate of %s", input$product_info_engagement_state), ylim = c(0, 120), xaxt = "n", axes = F, col = "dodgerblue")
  axis(side = 2, at = 20*(0:5), las = 2)
  
  text(barplot, par("usr")[3], labels = sub_rates[, get(product.name)], srt = 45, adj = c(1.1,1.1), xpd = TRUE)
  
  space_val = 0
  text(x = -0.4 + 1:sub_rates[,.N] * (1+space_val), y = sub_rates[,Mean], labels = sprintf("%.1f%%", sub_rates[, Mean]), pos = 3)
})
```


Question 3
=====================================  

Row {data-height=500}
-------------------------------------

```{r brand_perceptions}
inputPanel(
  selectInput(inputId="bp_age_group", label = "Age Group", choices = unique.age.groups, selected = unique.age.groups, multiple = TRUE),
  selectInput(inputId = "bp_gender", label = "Gender", choices = unique.genders, selected = unique.genders, multiple = TRUE),
  selectInput(inputId = "bp_income_group", label = "Income Group", choices = unique.income.groups, selected = unique.income.groups, multiple = TRUE),
  selectInput(inputId = "bp_region", label = "Region", choices = unique.regions, selected = unique.regions, multiple = TRUE),
  selectInput(inputId = "bp_persona", label = "Persona", choices = unique.personas, selected = unique.personas, multiple = TRUE),

  sliderInput(inputId = "bp_Top_products", label = "# of Products shown", min = 0, max = 20, value = 5, step = 1)
)

renderPlot({
  subdat <- dat[get(age.group.name) %in% input$bp_age_group & get(gender.name) %in% input$bp_gender & get(income.group.name) %in% input$bp_income_group & get(region.name) %in% input$bp_region & get(persona.name) %in% input$bp_persona]
  dat_bp <- subdat[,lapply(X = .SD, FUN = function(x)mean(x, na.rm = TRUE)), .SDcols = bp.traits, by = product.name]
  dat_bp_negative <- dat_bp[,lapply(X = .SD, FUN = function(x)(10-x)), .SDcols = negative_perceptions]
  dat_inverted_average <- cbind(dat_bp[,1:9],dat_bp_negative)
  dat_bp_overall <- dat_inverted_average[, .(Product = get(product.name), Overall_average = rowMeans(dat_inverted_average[,2:13],na.rm = TRUE))]
  setorderv(x = dat_bp_overall, cols = "Overall_average",-1)
  selected_bp_overall <- dat_bp_overall[1:input$bp_Top_products]
  sub_bp_overall <- selected_bp_overall[, Overall_average := round(x = Overall_average, digits = 1)]

  barplot <- barplot(height = sub_bp_overall[,Overall_average], space=0.01, las = 1, main = sprintf("Top %s brands of overall average perception", input$bp_Top_products), ylab = "Overall average perception", ylim = c(0, 12), xaxt = "n", axes = F, col = "dodgerblue")
  axis(side = 2, at = 2*(0:5), las = 2)
  
  text(barplot, par("usr")[3], labels = sub_bp_overall[, get(product.name)], srt = 45, adj = c(1.1,1.1), xpd = TRUE)
  
  space_val = 0
  text(x = -0.4 + 1:sub_bp_overall[,.N] * (1+space_val), y = sub_bp_overall[,Overall_average], labels = sub_bp_overall[,Overall_average], pos = 3)
})

```

Question 4
=====================================  

Row {data-height=500}
-------------------------------------

```{r engagement_plots}
inputPanel(
  selectInput(inputId="ep_first_outcome", label = "Select First Engagement:", choices = states.of.engagement, selected = states.of.engagement[1]),
  selectInput(inputId="ep_second_outcome", label = "Select Second Engagement:", choices = states.of.engagement, selected = states.of.engagement[2]),
  sliderInput(inputId="ep_digits", label = "Select Digits:", min = 0, max = 5, value = 1, step = 1),
  
  sliderInput(inputId = "ep_Top_products", label = "# of Top Products", min = 0, max = 20, value = 5, step = 1),

  checkboxInput(inputId = "ep_show_percentages", label = "Show Percentages", value = TRUE)
)

renderPlot({
  First_outcome = dat[, .(First_rate = 100*mean(get(input$ep_first_outcome),na.rm = TRUE)),by = product.name]
  Second_outcome = dat[, .(Second_rate = 100*mean(get(input$ep_second_outcome),na.rm = TRUE)),by = product.name]
  Subtab = merge(First_outcome, Second_outcome, by = product.name)
  Subtab[,gaps := First_rate - Second_rate]
  setorderv(x = Subtab, cols = "gaps",order = -1)
  
  rounded_Subtab = Subtab[, gaps := round(x = gaps, digits = input$ep_digits)]
  
  selected_Subtab = rounded_Subtab[1:input$ep_Top_products,]

  barplot <- barplot(height = selected_Subtab[,gaps], space=0.01, las = 1, main = sprintf("%s %s gaps top%s", input$ep_first_outcome, input$ep_second_outcome, input$ep_Top_products), ylab = "Differences as percentages", ylim = c(0, 120), xaxt = "n", axes = F, col = "dodgerblue", cex.lab = 0.8, cex.axis = 0.8)
  axis(side = 2, at = 20*(0:5), las = 2)
  
  text(barplot, par("usr")[3], labels = selected_Subtab[,get(product.name)], srt = 45, adj = c(1.1,1.1), xpd = TRUE, cex = 0.8)

  if(input$ep_show_percentages == TRUE){
  space_val = 0
  text(x = -0.4 + 1:selected_Subtab[,.N] * (1+space_val), y = selected_Subtab[,gaps], labels = paste0(selected_Subtab[,gaps],"%"), cex = 0.8, pos = 3)
  }
})
```

Question 5
=====================================  

Row {data-height=300}
-------------------------------------


```{r engagement_models}
inputPanel(
  selectInput(inputId = "em_product", label = "Select Product:", choices = unique.products, selected = product.name[1]),
  selectInput(inputId = "em_engagement_state", label = "Select State of Engagement:", choices = states.of.engagement, selected = states.of.engagement[1]),
  selectInput(inputId="em_inputs", label = "Choose Inputs:", choices = c(age.group.name, gender.name, income.group.name, region.name, persona.name, bp.traits, Aggregated.Engagement.name), selected = c(age.group.name, gender.name, income.group.name, region.name, persona.name, Aggregated.Engagement.name), multiple = TRUE)
)


renderDataTable({

  pattern.names <- list()
  for (i in 1:length(bp.traits)){
    pattern.names[[i]] <- names(dat)[grep(pattern = bp.traits[i],x = names(dat))]
   }

  subtable1 <- dat[get(product.name) == input$em_product,.SD,.SDcols = c(id.name, product.name, input$em_engagement_state, as.character(pattern.names), age.group.name, gender.name, income.group.name, region.name, persona.name)]
  subtable2 <- dat[get(product.name) != input$em_product,.(mean(get(input$em_engagement_state),na.rm = TRUE)),by = id]
  setnames(x = subtable2, old = "V1", new = eval(Aggregated.Engagement.name))
  
  aggregated_tab <- merge(subtable1,subtable2,by = eval(id.name))
  
  alpha = 0.05
  z <- qnorm(p = 1-alpha/2, mean = 0, sd = 1)

  outcome.name <- eval(input$em_engagement_state)

  if(input$em_engagement_state == awareness.name){
    input.name <- input$em_inputs[!input$em_inputs %in% bp.traits]
    }

  if(input$em_engagement_state != awareness.name){
    input.name <- input$em_inputs
    }

  formula <- sprintf("`%s` ~ %s", outcome.name, paste(lapply(input.name, FUN = function(x)sprintf("`%s`", x)), collapse = "+"))

  if (input$em_engagement_state == satisfaction.name){
    model <- lm(formula = as.formula(formula), data = aggregated_tab)
    model_coefs <- as.data.table(summary(model)$coefficients, keep.rownames = TRUE)
    model_coefs[, Coef.Lower.95 := Estimate - z * `Std. Error`]
    model_coefs[, Coef.Upper.95 := Estimate + z * `Std. Error`]

  }

  if (input$em_engagement_state != satisfaction.name){
    model <- glm(formula = as.formula(formula), family = "binomial", data = aggregated_tab)
    model_coefs <- as.data.table(summary(model)$coefficients, keep.rownames = TRUE)
    model_coefs[, Odds.Ratio := exp(Estimate)]
    model_coefs[, OR.Lower.95 := exp(Estimate - z * `Std. Error`)]
    model_coefs[, OR.Upper.95 := exp(Estimate + z * `Std. Error`)]

  }
  datatable(model_coefs[,lapply(X = .SD,FUN = "round.numerics", digits = 3)])
})
```

Row {data-height=700}
-------------------------------------